name: "ChromaDB"
version: "1.0.20"
slug: "chromadb"
description: "Self-hosted ChromaDB server for AI agents and local vector storage"
startup: services
boot: auto
init: false
host_network: true
hassio_api: false
homeassistant_api: false
arch:
  - amd64
  - aarch64

image: "ghcr.io/chroma-core/chroma"
image_tag: "1.0.14"

options:
  port: 8000
  disable_telemetry: true
  db_dir: "/data"

schema:
  port: int
  disable_telemetry: bool
  db_dir: str

environment:
  CHROMA_SERVER_HTTP_PORT: "!port"
  CHROMA_TELEMETRY_ENABLED: "!not disable_telemetry"
  CHROMA_DB_DIR: "!db_dir"

ports:
  8000/tcp: 8000

map:
  - config:rw
  - ssl:ro
  - share:rw
  - addons:rw
  - backup:rw

webui: "http://[HOST]:[PORT:8000]"
