name: "ChromaDB"
version: "0.5.5"
slug: "chromadb"
description: "Official ChromaDB image with configurable environment variables"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
image: "chromadb/chroma"
image_tag: "0.5.5"

options:
  port: 8000
  disable_telemetry: true

schema:
  port: int
  disable_telemetry: bool

environment:
  CHROMA_SERVER_HTTP_PORT: "${port}"
  CHROMA_TELEMETRY_ENABLED: "$!disable_telemetry"

host_network: true
