name: "ChromaDB"
version: "1.0.1"
slug: "chromadb"
description: "Official ChromaDB image with configurable options"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
image: "chromadb/chroma"
image_tag: "0.5.5"

options:
  port: 8000
  disable_telemetry: true

schema:
  port: int
  disable_telemetry: bool
