name: "ChromaDB"
version: "1.0.9"
slug: "chromadb"
description: "Self-hosted ChromaDB server for AI agents and local vector storage"
startup: services
boot: auto
init: false
host_network: true
hassio_api: false
homeassistant_api: false
arch:
  - amd64
  - aarch64
image: "ghcr.io/chroma-core/chroma"
image_tag: "latest"

options:
  port: 8000
  disable_telemetry: true

schema:
  port: int
  disable_telemetry: bool

map: []

environment:
  CHROMA_SERVER_HTTP_PORT: "!port"
  CHROMA_TELEMETRY_ENABLED: "!not disable_telemetry"

ports:
  8000/tcp: 8000

webui: "http://[HOST]:[PORT:8000]"
