name: "ChromaDB"
version: "1.0.0"
slug: "chromadb"
description: "Official ChromaDB image with minimal config"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
image: "chromadb/chroma:0.5.5"
options: {}
schema: {}
