name: "ChromaDB"
version: "0.5.5"
slug: "chromadb"
description: "Official ChromaDB image with minimal config"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
image: "chromadb/chroma"
image_tag: "0.5.5"
options: {}
schema: {}
